### ISSUE TITLE
No se muestran datos para una fecha en la parte de contrataciones pero sí en estadísticas

### ISSUE THREAD

**Issue by carlosfernandezcabrero** [franjpr/boe-frontend#21]
Hola, 

He observado que para una fecha dada la parte de estadísticas sí que muestra datos pero la de contratos no. Adjunto evidencias:
ESTADISTICAS:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56631428/190145134-14d05624-be71-4836-8f4e-233a39a80548.png">

CONTRATOS:
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/56631428/190145199-222cd999-87c4-4b30-9bcf-25cf2e7cdce4.png">

Un saludo, muchas gracias

**Comment by franjpr** [comment]
Hola!
Qué raro, ami sí me salen 🤔 
<img width="943" alt="image" src="https://user-images.githubusercontent.com/5502172/191681990-1d7ae88f-392a-4ef8-b259-e0dbdf532d28.png">
